repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

    - repo: https://github.com/psf/black-pre-commit-mirror
      rev: 26.3.1
      hooks:
          - id: black

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.20.1
      hooks:
        - id: mypy
          alias: mypy app
          name: Run mypy app
          language: system
          exclude: tests
          args: ["app"]

        - id: mypy
          alias: mypy mediaservice
          name: Run mypy mediaservice
          language: system
          exclude: tests
          args: ["mediaservice"]

        - id: mypy
          alias: mypy notification-service
          name: Run mypy notification-service
          language: system
          exclude: tests
          args: ["notification-service"]

        - id: mypy
          alias: mypy packages
          name: Run mypy packages
          language: system
          exclude: tests
          args: ["packages"]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.15.11
      hooks:
        - id: ruff-check
          args:
            - --fix
          exclude: tests
