services:
  movie-catalog:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: movie-catalog
    environment:
      DATABASE__HOST: database
      DATABASE__PORT: 5432

      REDIS__CONNECTION__HOST: redis
      REDIS__CONNECTION__PORT: 6379

      RABBITMQ__HOST: rabbitmq
      RABBITMQ__PORT: 5672
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mediaservice:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      start_period: 15s
      interval: 2s
      timeout: 2s
      retries: 3

  frontend:
    image: nginx:1.27-alpine
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      movie-catalog:
          condition: service_healthy

  database:
    image: postgres:17-bookworm
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie-catalog
    ports:
      - "5433:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d movie-catalog"]
      start_period: 3s
      interval: 2s
      timeout: 2s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"

  redis:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 1s
      interval: 2s
      timeout: 2s
      retries: 3

  redis_gui:
    image: redis/redisinsight
    container_name: redis_gui
    ports:
      - "5540:5540"

  rabbitmq:
    image: rabbitmq:4.3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      start_period: 2s
      interval: 2s
      timeout: 2s
      retries: 3

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      start_period: 3s
      interval: 2s
      timeout: 2s
      retries: 3

  mediaservice:
    build:
      context: .
      dockerfile: mediaservice/Dockerfile
    container_name: mediaservice
    environment:
      MINIO__HOST: minio
      MINIO__PORT: 9000
      MINIO__ACCESS_KEY: admin
      MINIO__SECRET_KEY: adminadmin
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      start_period: 3s
      interval: 2s
      timeout: 2s
      retries: 3
    depends_on:
      minio:
        condition: service_healthy


volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:
  minio-data:
