"""Add unique constraints to movies table

Revision ID: 03542bfa1ae4
Revises: 3db415545444
Create Date: 2026-05-23 10:49:22.967168

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "03542bfa1ae4"
down_revision: Union[str, Sequence[str], None] = "3db415545444"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_movies_name",
        "movies",
        ["name"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_movies_name",
        "movies",
        type_="unique",
    )
    # ### end Alembic commands ###
