"""increase encrypted_password column size

Revision ID: 04304e3a83ea
Revises: 59f73bee9615
Create Date: 2026-03-27 11:01:01.569603

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04304e3a83ea"
down_revision: str | Sequence[str] | None = "59f73bee9615"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "encrypted_password",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=128),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "encrypted_password",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
