"""Rework genre constraints

Revision ID: 209984e20c10
Revises: 3911694e554c
Create Date: 2026-05-23 14:54:09.253024

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "209984e20c10"
down_revision: Union[str, Sequence[str], None] = "3911694e554c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "genres",
        "name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=40),
        existing_nullable=False,
    )
    op.alter_column(
        "genres",
        "description",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=900),
        existing_nullable=False,
    )
    op.drop_constraint(
        "ch_genres_name",
        "genres",
        "check",
    )
    op.create_check_constraint(
        "ch_genres_name",
        "genres",
        "LENGTH(name) >= 3 AND LENGTH(name) <= 40",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "genres",
        "description",
        existing_type=sa.String(length=900),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "genres",
        "name",
        existing_type=sa.String(length=40),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.drop_constraint(
        "ch_genres_name",
        "genres",
        "check",
    )
    op.create_check_constraint(
        "ch_genres_name",
        "genres",
        "LENGTH(name) >= 3 AND LENGTH(name) <= 30",
    )
    # ### end Alembic commands ###
