"""Add more correct constraints to movies

Revision ID: 24c4c5225bf8
Revises: 209984e20c10
Create Date: 2026-05-23 15:31:05.726938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "24c4c5225bf8"
down_revision: Union[str, Sequence[str], None] = "209984e20c10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "movies",
        "name",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "movies",
        "description",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=2000),
        existing_nullable=True,
    )
    op.alter_column(
        "movies",
        "release_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        existing_nullable=False,
    )
    op.drop_constraint("ch_movies_name", "movies", type_="check")
    op.create_check_constraint(
        "ch_movies_name",
        "movies",
        "LENGTH(name) >= 3 AND LENGTH(name) <= 255",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "movies",
        "release_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "movies",
        "description",
        existing_type=sa.String(length=2000),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "movies",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_constraint(
        "ch_movies_name",
        "movies",
        type_="check",
    )
    op.create_check_constraint(
        "ch_movies_name",
        "movies",
        "LENGTH(name) >= 3 AND LENGTH(name) <= 20",
    )
    # ### end Alembic commands ###
