"""Add more precise restrictions to the reviews table

Revision ID: 3911694e554c
Revises: 03542bfa1ae4
Create Date: 2026-05-23 11:52:20.532665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3911694e554c"
down_revision: Union[str, Sequence[str], None] = "03542bfa1ae4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reviews",
        "review_text",
        existing_type=sa.VARCHAR(length=400),
        type_=sa.String(length=2000),
        existing_nullable=True,
    )
    op.drop_constraint(
        "ch_reviews_rating",
        "reviews",
        type_="check",
    )
    op.create_check_constraint(
        "ch_reviews_rating",
        "reviews",
        "rating >= 1 AND rating <= 10",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reviews",
        "review_text",
        existing_type=sa.String(length=2000),
        type_=sa.VARCHAR(length=400),
        existing_nullable=True,
    )
    op.drop_constraint(
        "ch_reviews_rating",
        "reviews",
        type_="check",
    )
    op.create_check_constraint(
        "ch_reviews_rating",
        "reviews",
        "rating >= 0 AND rating <= 10",
    )
    # ### end Alembic commands ###
