"""Add cascade delete to favorite movies table

Revision ID: 3db415545444
Revises: a98801dd614e
Create Date: 2026-05-22 08:09:36.589715

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3db415545444"
down_revision: Union[str, Sequence[str], None] = "a98801dd614e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_favorite_movies_user_id"),
        "favorite_movies",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_favorite_movies_movie_id"),
        "favorite_movies",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_favorite_movies_user_id",
        "favorite_movies",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_favorite_movies_movie_id",
        "favorite_movies",
        "movies",
        ["movie_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_favorite_movies_movie_id",
        "favorite_movies",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_favorite_movies_user_id",
        "favorite_movies",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_favorite_movies_movie_id"),
        "favorite_movies",
        "movies",
        ["movie_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_favorite_movies_user_id"),
        "favorite_movies",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
