"""add column description to genre

Revision ID: 4013e338295f
Revises: 3fcf16e16344
Create Date: 2026-03-23 09:10:24.284175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4013e338295f'
down_revision: Union[str, Sequence[str], None] = '3fcf16e16344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('description', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genres', 'description')
    # ### end Alembic commands ###
