"""Add constraint to genre name column

Revision ID: 45e2c2a31d5e
Revises: 81e5cc441619
Create Date: 2026-05-01 11:07:47.303372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "45e2c2a31d5e"
down_revision: Union[str, Sequence[str], None] = "81e5cc441619"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "genres",
        "name",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        "uq_genres_name",
        "genres",
        ["name"],
    )
    op.create_check_constraint(
        "ch_genres_name",
        "genres",
        "LENGTH(name) >= 3 AND LENGTH(name) <= 30",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ch_genres_name",
        "genres",
        type_="check",
    )
    op.drop_constraint(
        "uq_genres_name",
        "genres",
        type_="unique",
    )
    op.alter_column(
        "genres",
        "name",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
