"""Add preview_url field to genre table

Revision ID: 4636a016e2df
Revises: 9ae2079f7d1f
Create Date: 2026-05-20 06:11:56.361837

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4636a016e2df"
down_revision: Union[str, Sequence[str], None] = "9ae2079f7d1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "genres",
        sa.Column(
            "preview_url",
            sa.String(length=255),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("genres", "preview_url")
    # ### end Alembic commands ###
