"""Add constraints to user table fields

Revision ID: 653bea1df1b4
Revises: 45e2c2a31d5e
Create Date: 2026-05-09 14:35:27.993937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "653bea1df1b4"
down_revision: Union[str, Sequence[str], None] = "45e2c2a31d5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=40),
        existing_nullable=False,
    )

    op.create_check_constraint(
        "ch_users_surname",
        "users",
        "LENGTH(surname) >= 3 AND LENGTH(surname) <= 30",
    )
    op.create_check_constraint(
        "ch_users_name",
        "users",
        "LENGTH(name) >= 3 AND LENGTH(name) <= 20",
    )
    op.create_check_constraint(
        "ch_users_login",
        "users",
        "LENGTH(login) >= 3 AND LENGTH(login) <= 20",
    )
    op.create_check_constraint(
        "ch_users_email",
        "users",
        "LENGTH(email) >= 10 AND LENGTH(email) <= 40",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=40),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_constraint(
        "ch_users_surname",
        "users",
        type_="check",
    )
    op.drop_constraint(
        "ch_users_name",
        "users",
        type_="check",
    )
    op.drop_constraint(
        "ch_users_login",
        "users",
        type_="check",
    )
    op.drop_constraint(
        "ch_users_email",
        "users",
        type_="check",
    )
    # ### end Alembic commands ###
