"""Add constraint to review table: one user review on one movie

Revision ID: 78828545af40
Revises: 24c4c5225bf8
Create Date: 2026-05-26 00:52:48.727924

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "78828545af40"
down_revision: Union[str, Sequence[str], None] = "24c4c5225bf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_reviews_movie_id_user_id",
        "reviews",
        ["user_id", "movie_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_reviews_movie_id_user_id",
        "reviews",
        type_="unique",
    )
    # ### end Alembic commands ###
