"""Add constraints to review table fields

Revision ID: 9ae2079f7d1f
Revises: a68e6b5349a1
Create Date: 2026-05-09 21:36:33.083468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9ae2079f7d1f"
down_revision: Union[str, Sequence[str], None] = "a68e6b5349a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        constraint_name="ch_reviews_rating",
        table_name="reviews",
        condition="rating >= 0 AND rating <= 10",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        constraint_name="ch_reviews_rating",
        table_name="reviews",
        type_="check",
    )
    # ### end Alembic commands ###
