"""Add constraints to movie user table fields

Revision ID: a68e6b5349a1
Revises: 653bea1df1b4
Create Date: 2026-05-09 19:00:25.080815

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a68e6b5349a1"
down_revision: Union[str, Sequence[str], None] = "653bea1df1b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "movies",
        "name",
        existing_type=sa.VARCHAR(),
        existing_nullable=False,
        type_=sa.String(length=20),
        nullable=False,
    )
    op.alter_column(
        "movies",
        "description",
        existing_type=sa.VARCHAR(),
        existing_nullable=True,
        type_=sa.String(length=200),
        nullable=True,
    )
    op.alter_column(
        "movies",
        "preview_url",
        existing_type=sa.VARCHAR(),
        existing_nullable=False,
        type_=sa.String(length=255),
        nullable=False,
    )
    op.alter_column(
        "movies",
        "source_url",
        existing_type=sa.VARCHAR(),
        existing_nullable=False,
        type_=sa.String(length=255),
        nullable=False,
    )
    op.create_check_constraint(
        constraint_name="ch_movies_name",
        table_name="movies",
        condition="LENGTH(name) >= 3 AND LENGTH(name) <= 20",
    )
    op.create_check_constraint(
        constraint_name="ch_movies_rating",
        table_name="movies",
        condition="rating >= 0 AND rating <= 10",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "movies",
        "name",
        existing_type=sa.VARCHAR(length=20),
        existing_nullable=False,
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "movies",
        "description",
        existing_type=sa.VARCHAR(length=200),
        existing_nullable=True,
        type_=sa.String(),
        nullable=True,
    )
    op.alter_column(
        "movies",
        "preview_url",
        existing_type=sa.VARCHAR(length=255),
        existing_nullable=False,
        type_=sa.String(),
        nullable=False,
    )
    op.alter_column(
        "movies",
        "source_url",
        existing_type=sa.VARCHAR(length=255),
        existing_nullable=False,
        type_=sa.String(),
        nullable=False,
    )
    op.drop_constraint(
        constraint_name="ch_movies_name",
        table_name="movies",
        type_="check",
    )
    op.drop_constraint(
        constraint_name="ch_movies_rating",
        table_name="movies",
        type_="check",
    )
    # ### end Alembic commands ###
