"""Add cascade delete to reviews table

Revision ID: a98801dd614e
Revises: a9e1a636724a
Create Date: 2026-05-22 07:53:35.344098

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a98801dd614e"
down_revision: Union[str, Sequence[str], None] = "a9e1a636724a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_reviews_user_id"),
        "reviews",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_reviews_movie_id"),
        "reviews",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_reviews_movie_id",
        "reviews",
        "movies",
        ["movie_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_reviews_user_id",
        "reviews",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_reviews_user_id",
        "reviews",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_reviews_movie_id",
        "reviews",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_reviews_movie_id"),
        "reviews",
        "movies",
        ["movie_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_reviews_user_id"),
        "reviews",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
