"""Add cascade delete to watch_history table

Revision ID: a9e1a636724a
Revises: 4636a016e2df
Create Date: 2026-05-22 07:32:54.779732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a9e1a636724a"
down_revision: Union[str, Sequence[str], None] = "4636a016e2df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_watch_history_user_id"),
        "watch_history",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_watch_history_movie_id"),
        "watch_history",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_watch_history_movie_id",
        "watch_history",
        "movies",
        ["movie_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_watch_history_user_id",
        "watch_history",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_watch_history_user_id",
        "watch_history",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_watch_history_movie_id",
        "watch_history",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_watch_history_movie_id"),
        "watch_history",
        "movies",
        ["movie_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_watch_history_user_id"), "watch_history", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
