"""update movie table

Revision ID: b835ae503cdd
Revises: 0029a40d4706
Create Date: 2026-03-22 16:07:34.640245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b835ae503cdd'
down_revision: Union[str, Sequence[str], None] = '0029a40d4706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('preview_url', sa.String(), nullable=False))
    op.add_column('movies', sa.Column('source_url', sa.String(), nullable=False))
    op.alter_column('movies', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('movies', 'source_url')
    op.drop_column('movies', 'preview_url')
    # ### end Alembic commands ###
