"""create table favorite_movies

Revision ID: bcb01ee3eaca
Revises: 1566e40c738c
Create Date: 2026-04-09 13:07:35.205498

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcb01ee3eaca"
down_revision: str | Sequence[str] | None = "1566e40c738c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("favorite_movies",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("movie_id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], name="fk_favorite_movies_movie_id"),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_favorite_movies_user_id"),
    sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("favorite_movies")
    # ### end Alembic commands ###
