"""Add uniuque constraint to users

Revision ID: cb71650c1185
Revises: f047955d7698
Create Date: 2026-05-26 13:22:51.353874

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cb71650c1185"
down_revision: Union[str, Sequence[str], None] = "f047955d7698"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_users_email",
        "users",
        ["email"],
    )
    op.create_unique_constraint(
        "uq_users_login",
        "users",
        ["login"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_users_login",
        "users",
        type_="unique",
    )
    op.drop_constraint(
        "uq_users_email",
        "users",
        type_="unique",
    )
    # ### end Alembic commands ###
