"""Add unique constraint to favorite movies on pair (user_id, movie_id)

Revision ID: f047955d7698
Revises: 78828545af40
Create Date: 2026-05-26 12:01:43.026276

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f047955d7698"
down_revision: Union[str, Sequence[str], None] = "78828545af40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_favorite_movies_movie_id_user_id",
        "favorite_movies",
        ["user_id", "movie_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_favorite_movies_movie_id_user_id",
        "favorite_movies",
        type_="unique",
    )
    # ### end Alembic commands ###
