name: python-checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repository
        uses: actions/checkout@v6

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync --dev

      - name: Run black
        run: uv run black .

      - name: Run mypy
        run: uv run mypy .

      - name: Run ruff
        run: uv run ruff check --fix

  testing:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit
