name: Test CI
on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CI works
        run: echo "CI is working!"
